"""phase7_foundation

Revision ID: aab74a41ee9e
Revises: ff5815e68ab3
Create Date: 2026-06-21 20:03:22.376236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab74a41ee9e'
down_revision: Union[str, None] = 'ff5815e68ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_health_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_health_log_id'), 'camera_health_log', ['id'], unique=False)
    op.add_column('alerts', sa.Column('status', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_by', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'alerts', 'users', ['acknowledged_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'acknowledged_at')
    op.drop_column('alerts', 'acknowledged_by')
    op.drop_column('alerts', 'status')
    op.drop_index(op.f('ix_camera_health_log_id'), table_name='camera_health_log')
    op.drop_table('camera_health_log')
    # ### end Alembic commands ###
