"""Add Camera source fields

Revision ID: ff5815e68ab3
Revises: 9f1e675be36b
Create Date: 2026-06-20 22:57:47.616741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5815e68ab3'
down_revision: Union[str, None] = '9f1e675be36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('cameras', sa.Column('stream_url', sa.String(), nullable=False))
    op.add_column('cameras', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.drop_column('cameras', 'rtsp_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('rtsp_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('cameras', 'last_seen')
    op.drop_column('cameras', 'stream_url')
    op.drop_column('cameras', 'source_type')
    # ### end Alembic commands ###
